=== Skillnet-test/armani/Armani/rpos/files_ind/prod/javapos/armani/conf/iSeriesConfig.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT iSeries (signed,address,user,password,libraries,timeout, secure, procedure, proceduredefault, proxy, proxyaddress)>
<!ELEMENT signed (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT libraries (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT secure (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT proceduredefault (#PCDATA)>
<!ELEMENT proxy (#PCDATA)>
<!ELEMENT proxyaddress (#PCDATA)>

=== Skillnet-test/armani/Armani/rpos/files_eur/prod/javapos/armani/conf/iSeriesConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iSeries SYSTEM "iSeriesConfig.dtd">
<!--Armani iSeries XML configuration -->
<!--  (C) C.S.A. s.r.l. -->
<!--  Author : Vincenzo Amoruso -->
<iSeries>
<signed>200503101520</signed>
<address>172.27.1.50</address>
<user>RETEK</user>
<password>KETER123</password>
<libraries>ARMANI,KLDADB</libraries>
<timeout>10</timeout>
<secure>false</secure>
<procedure>{CALL KLDADB.GETNEWCOD(?)}</procedure>
<proceduredefault>{CALL KLDADB.GETDFTCOD( ?, ?, ?, ?, ?)}</proceduredefault>
<proxy>no</proxy>
<proxyaddress>0.0.0.0</proxyaddress>
</iSeries>

=== Skillnet-test/armani/Armani/rpos/files_eur/prod/javapos/armani/conf/iSeriesConfigarm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iSeries SYSTEM "iSeriesConfig.dtd">
<!--Armani iSeries XML configuration -->
<!--  (C) C.S.A. s.r.l. -->
<!--  Author : Vincenzo Amoruso -->
<iSeries>
<signed>200503101520</signed>
<address>192.192.194.50</address>
<user>JAVAWEB</user>
<password>5NYQ2KP/uO8=</password>
<libraries>MODARM,KLDADB</libraries>
<timeout>10</timeout>
<secure>false</secure>
<procedure>{CALL KLDADB.GETNEWCOD(?)}</procedure>
<proxy>no</proxy>
<proxyaddress>0.0.0.0</proxyaddress>
</iSeries>

=== Skillnet-test/armani/Armani/rpos/files_eur/prod/javapos/armani/conf/iSeriesConfigcsa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iSeries SYSTEM "iSeriesConfig.dtd">
<!--Armani iSeries XML configuration -->
<!--  (C) C.S.A. s.r.l. -->
<!--  Author : Vincenzo Amoruso -->
<iSeries>
<signed>200503101520</signed>
<address>192.192.193.32</address>
<user>VINCENZO</user>
<password>mastro72</password>
<libraries>ARMANI,QGPL</libraries>
<timeout>10</timeout>
<secure>false</secure>
<procedure>{CALL ARMANI.GETNEWCOD(?)}</procedure>
<proxy>no</proxy>
<proxyaddress>192.192.194.217</proxyaddress>
</iSeries>
