=== Skillnet-test/armani/Armani/rpos/files_eur/prod/javapos/armani/document.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="intero">
	<xs:restriction base="xs:positiveInteger"/>
</xs:simpleType>

<xs:simpleType name="decimale">
	<xs:restriction base="xs:decimal"/>
</xs:simpleType>

<xs:simpleType name="percentuale">
	<xs:restriction base="xs:decimal">
	<xs:minInclusive value="0"/>
	<xs:maxInclusive value="100"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="DocID">
	<xs:restriction base="xs:string">
	<xs:enumeration value="SCF"/> 
	<xs:enumeration value="DDT"/> 
	<xs:enumeration value="FAT"/> 
	<xs:enumeration value="NCR"/> 
	<xs:enumeration value="TAX"/> 
	<xs:enumeration value="OTH"/> 
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="anagraphic">
	<xs:sequence>
		<xs:element name="Type" 		type="xs:string" minOccurs="0"/>
		<xs:element name="Code" 		type="xs:string"/>
		<xs:element name="Descr" 		type="xs:string" minOccurs="0"/>
		<xs:element name="Title" 		type="xs:string" minOccurs="0"/>
		<xs:element name="Surname" 		type="xs:string"/>
		<xs:element name="Name" 		type="xs:string"/>
		<xs:element name="Address" 		type="xs:string"/>
		<xs:element name="City" 		type="xs:string"/>
		<xs:element name="Country" 		type="xs:string"/>
		<xs:element name="CountryCode" 	type="xs:string"/>
		<xs:element name="Zip" 			type="xs:string"/>
		<xs:element name="State" 		type="xs:string" minOccurs="0"/>
		<xs:element name="StateCode" 	type="xs:string" minOccurs="0"/>
		<xs:element name="IdType" 		type="xs:string"/>
		<xs:element name="IdNumber" 	type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="documentkey">
<xs:sequence>
	<xs:element name="DocType"   type="DocID"/>
	<xs:element name="DocNumber" type="xs:string"/>
	<xs:element name="DocDate"   type="xs:date"/>
	<xs:element name="DocName"   type="xs:string"	minOccurs="0"/>
	<xs:element name="OwnerCode" type="xs:string"/>
	<xs:element name="DocNote"   type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="paymenttype">
<xs:sequence>
	<xs:element name="RowNo" 		type="intero"/> 
	<xs:element name="Code" 		type="xs:string"/> 
	<xs:element name="CodeDescr" 	type="xs:string"/> 
	<xs:element name="Currency" 	type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Value" 		type="decimale" 	minOccurs="0"/> 
	<xs:element name="Date" 		type="xs:date" 		minOccurs="0"/> 
	<xs:element name="Note" 		type="xs:string"/> 
</xs:sequence>
</xs:complexType>

<xs:complexType name="rowtype">
<xs:sequence>
	<xs:element name="RowNo"			type="intero"/> 
	<xs:element name="Descr"			type="xs:string"/> 
	<xs:element name="PackType" 		type="xs:string" 	minOccurs="0"/> 
	<xs:element name="PackDescr" 		type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Qty" 				type="decimale"/> 
	<xs:element name="Currency" 		type="xs:string"/> 
	<xs:element name="Price" 			type="decimale"/> 
	<xs:element name="Vat" 				type="decimale"/> 
	<xs:element name="VatPerc" 			type="percentuale"/> 
	<xs:element name="VatNet" 			type="decimale"/> 
	<xs:element name="Discount01" 		type="decimale" 	minOccurs="0"/> 
	<xs:element name="Discount02" 		type="decimale" 	minOccurs="0"/> 
	<xs:element name="Discount03" 		type="decimale" 	minOccurs="0"/> 
	<xs:element name="Discount01Desc" 	type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Discount02Desc" 	type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Discount03Desc" 	type="xs:string" 	minOccurs="0"/> 
	<xs:element name="FinalPrice" 		type="decimale"/> 
	<xs:element name="TotalPrice" 		type="decimale"/> 
	<xs:element name="Cost" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="Refund" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="RefundType" 		type="xs:string" 	minOccurs="0"/> 
	<xs:element name="PackNo" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="Weight" 			type="decimale"		minOccurs="0"/> 
	<xs:element name="Desc01" 			type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Desc02" 			type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Desc03" 			type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Desc04" 			type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Desc05" 			type="xs:string" 	minOccurs="0"/> 
	<xs:element name="Value01" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="Value02" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="Value03" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="Value04" 			type="decimale" 	minOccurs="0"/> 
	<xs:element name="Value05" 			type="decimale" 	minOccurs="0"/> 
</xs:sequence>
</xs:complexType>

<xs:complexType name="expeditiontype">
<xs:sequence>
	<xs:element name="ExpeditionCode"  type="xs:string" minOccurs="0"/>
	<xs:element name="ExpeditionDescr" type="xs:string"/>
	<xs:element name="ExpeditionNo"    type="xs:string"/>
	<xs:element name="ExpeditionDate"  type="xs:date"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="totaltype">
<xs:sequence>
	<xs:element name="TotalQty"        type="xs:string"/>
	<xs:element name="Currency"        type="xs:string"/>
	<xs:element name="TotalPrice"      type="decimale"/>
	<xs:element name="TotalDiscount"   type="decimale"/>
	<xs:element name="TotalFinalPrice" type="decimale"/>
	<xs:element name="TotalVat"        type="decimale"/>
	<xs:element name="TotalNet"        type="decimale"/>
	<xs:element name="TotalCost"       type="decimale"	minOccurs="0"/>
	<xs:element name="TotalRefund"     type="decimale"/>
	<xs:element name="RefDocundType"   type="xs:string" minOccurs="0"/>
	<xs:element name="DocPackType"     type="xs:string" minOccurs="0"/>
	<xs:element name="DocPackDesc"     type="xs:string" minOccurs="0"/>
	<xs:element name="DocPackNo"       type="intero"/>
	<xs:element name="TotalWeight"     type="decimale"/>
</xs:sequence>
</xs:complexType>

<xs:element name="Document">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Customer" 	type="anagraphic"	maxOccurs="1" />
		<xs:element name="Owner" 		type="anagraphic"	maxOccurs="1" />
		<xs:element name="refCustomer"	type="anagraphic"	maxOccurs="1" />
		<xs:element name="refDocument"	type="documentkey"	maxOccurs="1" />
		<xs:element name="Destination" 	type="anagraphic"	maxOccurs="1" />
		<xs:element name="Carrier" 		type="anagraphic" 	maxOccurs="1" />
		<xs:element name="key" 			type="documentkey"	maxOccurs="1" />
		<xs:element name="Expedition"	type="expeditiontype" minOccurs="0" maxOccurs="1" />
		<xs:element name="Totals"       type="totaltype"	maxOccurs="1" />
		<xs:element name="DocDescr01"   type="xs:string"	minOccurs="0" />
		<xs:element name="DocValue01"   type="decimale"		minOccurs="0" /> 
		<xs:element name="DocDescr02"   type="xs:string" 	minOccurs="0" />
		<xs:element name="DocValue02"   type="decimale" 	minOccurs="0" /> 
		<xs:element name="DocDescr03"   type="xs:string" 	minOccurs="0" />
		<xs:element name="DocValue03"   type="decimale" 	minOccurs="0" /> 
		<xs:element name="DocDescr04"   type="xs:string" 	minOccurs="0" />
		<xs:element name="DocValue04"   type="decimale" 	minOccurs="0" /> 
		<xs:element name="DocDescr05"   type="xs:string" 	minOccurs="0" />
		<xs:element name="DocValue05"   type="decimale" 	minOccurs="0" /> 
		<xs:element name="Payment" 		type="paymenttype"	minOccurs="0" maxOccurs="unbounded" />		
		<xs:element name="Row" 			type="rowtype"		minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Skillnet-test/armani/Armani/rpos/files_eur/prod/javapos/armani/BaseDocument.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../files/prod/javapos/armani/document.xsd">
  <Customer>
    <Type>Type</Type>
    <Code>Code</Code>
    <Descr>Descr</Descr>
    <Title>Title</Title>
    <Surname>Surname</Surname>
    <Name>Name</Name>
    <Address>Address</Address>
    <City>City</City>
    <Country>Country</Country>
    <CountryCode>CountryCode</CountryCode>
    <Zip>Zip</Zip>
    <State>State</State>
    <StateCode>StateCode</StateCode>
    <IdType>IdType</IdType>
    <IdNumber>IdNumber</IdNumber>
  </Customer>
  <Owner>
    <Type>Type</Type>
    <Code>Code</Code>
    <Descr>Descr</Descr>
    <Title>Title</Title>
    <Surname>Surname</Surname>
    <Name>Name</Name>
    <Address>Address</Address>
    <City>City</City>
    <Country>Country</Country>
    <CountryCode>CountryCode</CountryCode>
    <Zip>Zip</Zip>
    <State>State</State>
    <StateCode>StateCode</StateCode>
    <IdType>IdType</IdType>
    <IdNumber>IdNumber</IdNumber>
  </Owner>
  <refCustomer>
    <Type>Type</Type>
    <Code>Code</Code>
    <Descr>Descr</Descr>
    <Title>Title</Title>
    <Surname>Surname</Surname>
    <Name>Name</Name>
    <Address>Address</Address>
    <City>City</City>
    <Country>Country</Country>
    <CountryCode>CountryCode</CountryCode>
    <Zip>Zip</Zip>
    <State>State</State>
    <StateCode>StateCode</StateCode>
    <IdType>IdType</IdType>
    <IdNumber>IdNumber</IdNumber>
  </refCustomer>
  <refDocument>
    <DocType>SCF</DocType>
    <DocNumber>DocNumber</DocNumber>
    <DocDate>2005-04-20</DocDate>
    <DocName>DocName</DocName>
    <OwnerCode>OwnerCode</OwnerCode>
    <DocNote>DocNote</DocNote>
  </refDocument>
  <Destination>
    <Type>Type</Type>
    <Code>Code</Code>
    <Descr>Descr</Descr>
    <Title>Title</Title>
    <Surname>Surname</Surname>
    <Name>Name</Name>
    <Address>Address</Address>
    <City>City</City>
    <Country>Country</Country>
    <CountryCode>CountryCode</CountryCode>
    <Zip>Zip</Zip>
    <State>State</State>
    <StateCode>StateCode</StateCode>
    <IdType>IdType</IdType>
    <IdNumber>IdNumber</IdNumber>
  </Destination>
  <Carrier>
    <Type>Type</Type>
    <Code>Code</Code>
    <Descr>Descr</Descr>
    <Title>Title</Title>
    <Surname>Surname</Surname>
    <Name>Name</Name>
    <Address>Address</Address>
    <City>City</City>
    <Country>Country</Country>
    <CountryCode>CountryCode</CountryCode>
    <Zip>Zip</Zip>
    <State>State</State>
    <StateCode>StateCode</StateCode>
    <IdType>IdType</IdType>
    <IdNumber>IdNumber</IdNumber>
  </Carrier>
  <key>
    <DocType>SCF</DocType>
    <DocNumber>DocNumber</DocNumber>
    <DocDate>2005-04-20</DocDate>
    <DocName>DocName</DocName>
    <OwnerCode>OwnerCode</OwnerCode>
    <DocNote>DocNote</DocNote>
  </key>
  <Expedition>
    <ExpeditionCode>ExpeditionCode</ExpeditionCode>
    <ExpeditionDescr>ExpeditionDescr</ExpeditionDescr>
    <ExpeditionNo>ExpeditionNo</ExpeditionNo>
    <ExpeditionDate>2005-04-20</ExpeditionDate>
  </Expedition>
  <Totals>
    <TotalQty>TotalQty</TotalQty>
    <Currency>Currency</Currency>
    <TotalPrice>0.0</TotalPrice>
    <TotalDiscount>0.0</TotalDiscount>
    <TotalFinalPrice>0.0</TotalFinalPrice>
    <TotalVat>0.0</TotalVat>
    <TotalNet>0.0</TotalNet>
    <TotalCost>0.0</TotalCost>
    <TotalRefund>0.0</TotalRefund>
    <RefDocundType>RefDocundType</RefDocundType>
    <DocPackType>DocPackType</DocPackType>
    <DocPackDesc>DocPackDesc</DocPackDesc>
    <DocPackNo>1</DocPackNo>
    <TotalWeight>0.0</TotalWeight>
  </Totals>
  <DocDescr01>DocDescr01</DocDescr01>
  <DocValue01>0.0</DocValue01>
  <DocDescr02>DocDescr02</DocDescr02>
  <DocValue02>0.0</DocValue02>
  <DocDescr03>DocDescr03</DocDescr03>
  <DocValue03>0.0</DocValue03>
  <DocDescr04>DocDescr04</DocDescr04>
  <DocValue04>0.0</DocValue04>
  <DocDescr05>DocDescr05</DocDescr05>
  <DocValue05>0.0</DocValue05>
  <Payment1>
    <RowNo>1</RowNo>
    <Code>Code</Code>
    <CodeDescr>CodeDescr</CodeDescr>
    <Currency>Currency</Currency>
    <Value>0.0</Value>
    <Date>2005-04-20</Date>
    <Note>Note</Note>
  </Payment1>
  <Payment2>
    <RowNo>1</RowNo>
    <Code>Code</Code>
    <CodeDescr>CodeDescr</CodeDescr>
    <Currency>Currency</Currency>
    <Value>0.0</Value>
    <Date>2005-04-20</Date>
    <Note>Note</Note>
  </Payment2>
  <Row1>
    <RowNo>1</RowNo>
    <Descr>Descr</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>0.0</Qty>
    <Currency>Currency</Currency>
    <Price>0.0</Price>
    <Vat>0.0</Vat>
    <VatPerc>0.0</VatPerc>
    <VatNet>0.0</VatNet>
    <Discount01>0.0</Discount01>
    <Discount02>0.0</Discount02>
    <Discount03>0.0</Discount03>
    <Discount01Desc>Discount01Desc</Discount01Desc>
    <Discount02Desc>Discount02Desc</Discount02Desc>
    <Discount03Desc>Discount03Desc</Discount03Desc>
    <FinalPrice>0.0</FinalPrice>
    <TotalPrice>0.0</TotalPrice>
    <Cost>0.0</Cost>
    <Refund>0.0</Refund>
    <RefundType>RefundType</RefundType>
    <PackNo>0.0</PackNo>
    <Weight>0.0</Weight>
    <Desc01>Desc01</Desc01>
    <Desc02>Desc02</Desc02>
    <Desc03>Desc03</Desc03>
    <Desc04>Desc04</Desc04>
    <Desc05>Desc05</Desc05>
    <Value01>0.0</Value01>
    <Value02>0.0</Value02>
    <Value03>0.0</Value03>
    <Value04>0.0</Value04>
    <Value05>0.0</Value05>
  </Row1>
  <Row2>
    <RowNo>1</RowNo>
    <Descr>Descr</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>0.0</Qty>
    <Currency>Currency</Currency>
    <Price>0.0</Price>
    <Vat>0.0</Vat>
    <VatPerc>0.0</VatPerc>
    <VatNet>0.0</VatNet>
    <Discount01>0.0</Discount01>
    <Discount02>0.0</Discount02>
    <Discount03>0.0</Discount03>
    <Discount01Desc>Discount01Desc</Discount01Desc>
    <Discount02Desc>Discount02Desc</Discount02Desc>
    <Discount03Desc>Discount03Desc</Discount03Desc>
    <FinalPrice>0.0</FinalPrice>
    <TotalPrice>0.0</TotalPrice>
    <Cost>0.0</Cost>
    <Refund>0.0</Refund>
    <RefundType>RefundType</RefundType>
    <PackNo>0.0</PackNo>
    <Weight>0.0</Weight>
    <Desc01>Desc01</Desc01>
    <Desc02>Desc02</Desc02>
    <Desc03>Desc03</Desc03>
    <Desc04>Desc04</Desc04>
    <Desc05>Desc05</Desc05>
    <Value01>0.0</Value01>
    <Value02>0.0</Value02>
    <Value03>0.0</Value03>
    <Value04>0.0</Value04>
    <Value05>0.0</Value05>
  </Row2>
  <Row3>
    <RowNo>1</RowNo>
    <Descr>Descr</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>0.0</Qty>
    <Currency>Currency</Currency>
    <Price>0.0</Price>
    <Vat>0.0</Vat>
    <VatPerc>0.0</VatPerc>
    <VatNet>0.0</VatNet>
    <Discount01>0.0</Discount01>
    <Discount02>0.0</Discount02>
    <Discount03>0.0</Discount03>
    <Discount01Desc>Discount01Desc</Discount01Desc>
    <Discount02Desc>Discount02Desc</Discount02Desc>
    <Discount03Desc>Discount03Desc</Discount03Desc>
    <FinalPrice>0.0</FinalPrice>
    <TotalPrice>0.0</TotalPrice>
    <Cost>0.0</Cost>
    <Refund>0.0</Refund>
    <RefundType>RefundType</RefundType>
    <PackNo>0.0</PackNo>
    <Weight>0.0</Weight>
    <Desc01>Desc01</Desc01>
    <Desc02>Desc02</Desc02>
    <Desc03>Desc03</Desc03>
    <Desc04>Desc04</Desc04>
    <Desc05>Desc05</Desc05>
    <Value01>0.0</Value01>
    <Value02>0.0</Value02>
    <Value03>0.0</Value03>
    <Value04>0.0</Value04>
    <Value05>0.0</Value05>
  </Row3>
</Document>

=== Skillnet-test/armani/Armani/rpos/files_eur/prod/javapos/armani/conf/InvoiceDocument.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Document xsi:noNamespaceSchemaLocation="Document.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Customer>
    <Type>Type</Type>
    <Code>Code</Code>
    <CodeDescr>CodeDescr</CodeDescr>
    <Title>SIG.</Title>
    <Surname>ROSSI</Surname>
    <Name>MARIO</Name>
    <Address>VIALE CARRARA CALA ARCIPRETE 11</Address>
    <City>ROMA</City>
    <Country>ITALY</Country>
    <CountryCode>ITA</CountryCode>
    <Zip>000100</Zip>
    <State></State>
    <StateCode>StateCode</StateCode>
    <IdType>PI</IdType>
    <IdNumber>123456789012345</IdNumber>
  </Customer>
  <Owner>
    <Type>Type</Type>
    <Code>Code</Code>
    <CodeDescr>emporio armani</CodeDescr>
    <Title>Title</Title>
    <Surname>Brambilla</Surname>
    <Name>Mario</Name>
    <Address>viale ceccarini 10-12</Address>
    <City>Riccione</City>
    <Country>ITALY</Country>
    <CountryCode>ITA</CountryCode>
    <Zip>10001</Zip>
    <State></State>
    <StateCode>StateCode</StateCode>
    <IdType>PI</IdType>
    <IdNumber>IdNumber</IdNumber>
  </Owner>
   <Header>
    <DocType>FAT</DocType>
    <DocNumber>1234567890123</DocNumber>
    <DocDate>2005-03-21 00:00:00</DocDate>
    <DocName>Fattura</DocName>
    <OwnerCode>OwnerCode</OwnerCode>
    <DocNote>DS52000219 SCONT.FISC.N. 16</DocNote>
    <TotalQty>70.00</TotalQty>
    <Currency>EUR</Currency>
    <TotalPrice>7.57</TotalPrice>
    <TotalDiscount>1.01</TotalDiscount>
    <TotalFinalPrice>299.92</TotalFinalPrice>
    <TotalVat>12.09</TotalVat>
    <TotalNet>27.80</TotalNet>
    <TotalRefund>0.98</TotalRefund>
    <RefundType>RefDocundType</RefundType>
    <DocPackType>DocPackType</DocPackType>
    <DocPackDesc>DocPackDesc</DocPackDesc>
    <DocPackNo>1</DocPackNo>
    <TotalWeight>3.00</TotalWeight>
  </Header>
  <Row>
    <RowNo>1</RowNo>
    <Descr>Articolo 1</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>2.00</Qty>
    <Currency>EUR</Currency>
    <Price>3.25</Price>
    <Vat>1.04</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>5.20</VatNet>
    <FinalPrice>3.25</FinalPrice>
    <TotalPrice>6.24</TotalPrice>
    <Refund>0.01</Refund>
    <RefundType>RefundType</RefundType>
  </Row>
  <Row>
    <RowNo>2</RowNo>
    <Descr>Articolo 2</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund>0.01</Refund>
    <RefundType>RefundType</RefundType>
  </Row>
<Row>
    <RowNo>3</RowNo>
    <Descr>Articolo 3</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>4</RowNo>
    <Descr>Articolo 4</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>5</RowNo>
    <Descr>Articolo 5</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>6</RowNo>
    <Descr>Articolo 6</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>7</RowNo>
    <Descr>Articolo 7</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>8</RowNo>
    <Descr>Articolo 8</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>9</RowNo>
    <Descr>Articolo 9</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>10</RowNo>
    <Descr>Articolo 10</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>11</RowNo>
    <Descr>Articolo 11</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>12</RowNo>
    <Descr>Articolo 12</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>13</RowNo>
    <Descr>Articolo 13</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>14</RowNo>
    <Descr>Articolo 14</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>15</RowNo>
    <Descr>Articolo 15</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>16</RowNo>
    <Descr>Articolo 16</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>17</RowNo>
    <Descr>Articolo 17</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat>2.88</Vat>
    <VatPerc>20</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>17.28</TotalPrice>
    <Refund></Refund>
    <RefundType>RefundType</RefundType>
  </Row><Row>
    <RowNo>18</RowNo>
    <Descr>Articolo 18</Descr>
    <PackType>PackType</PackType>
    <PackDescr>PackDescr</PackDescr>
    <Qty>4.00</Qty>
    <Currency>EUR</Currency>
    <Price>4.32</Price>
    <Vat></Vat>
    <VatPerc>N.I.</VatPerc>
    <VatNet>14.40</VatNet>
    <FinalPrice>4.32</FinalPrice>
    <TotalPrice>14.40</TotalPrice>
    <Refund>0.01</Refund>
    <RefundType>RefundType</RefundType>
  </Row>
  </Document>
